#!/bin/bash

while getopts e: flag
do
	case "${flag}" in
		e) emotion=${OPTARG};;
	esac
done

for file in /home/ram/Pictures/AI_Images/$emotion/*
	do face-mask /"$file"
done

maskdir="${emotion}_mask"

mkdir /home/ram/Pictures/AI_Images/$maskdir

mv /home/ram/Pictures/AI_Images/$emotion/?*-with-mask.png /home/ram/Pictures/AI_Images/$maskdir
